include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart, lib/**.gen.dart ]
linter:
  rules:
    public_member_api_docs: false
